# Generated by Django 3.2 on 2023-09-28 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_positions', models.CharField(choices=[('Bricklayers and masons', 'Bricklayers and masons'), ('Roofers, roof tilers and slaters', 'Roofers, roof tilers and slaters'), ('Carpenters and joiners', 'Carpenters and joiners'), ('Construction and building trades', 'Construction and building trades'), ('Plasterers including dry liners', 'Plasterers including dry liners'), ('Floorers and wall tilers', 'Floorers and wall tilers')], max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('highest_level_of_education', models.CharField(max_length=100)),
                ('school_university_name', models.CharField(max_length=100)),
                ('degree_earned', models.CharField(max_length=100)),
                ('year_of_graduation', models.CharField(max_length=100)),
                ('previous_job_title', models.CharField(max_length=100)),
                ('dates_employed', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('relevant_certifications', models.TextField()),
                ('computer_skills', models.TextField()),
                ('reference1_name', models.CharField(max_length=100)),
                ('reference1_phone_number', models.CharField(max_length=100)),
                ('reference1_email', models.EmailField(max_length=254)),
                ('reference2_name', models.CharField(max_length=100)),
                ('reference2_phone_number', models.CharField(max_length=100)),
                ('reference2_email', models.EmailField(max_length=254)),
                ('how_did_you_hear_about_us', models.CharField(max_length=100)),
                ('why_do_you_want_to_work_for_us', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc'])])),
                ('cover_letter', models.FileField(upload_to='cover_letters/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'jpg', 'png'])])),
                ('signature', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
