# Generated by Django 3.2 on 2023-09-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form_id',
            field=models.CharField(default='kljdaflkasjkl45k67', max_length=100),
            preserve_default=False,
        ),
    ]
