# Generated by Django 3.2 on 2023-09-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_application_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='signature',
        ),
    ]
