# Generated by Django 3.2 on 2023-09-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_application_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(help_text='Phone Number. Please include country code. e.g +44', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='reference1_phone_number',
            field=models.CharField(help_text='Phone Number. Please include country code. e.g +44', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='reference2_phone_number',
            field=models.CharField(help_text='Phone Number. Please include country code. e.g +44', max_length=100),
        ),
    ]
