# Generated by Django 3.2 on 2023-09-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230929_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dates_employed',
            field=models.CharField(default=2024, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='end_date',
            field=models.CharField(default=2024, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='year_of_graduation',
            field=models.CharField(default=2024, max_length=100),
        ),
    ]
