# Generated by Django 3.2 on 2023-09-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230929_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='eritten', max_length=100),
            preserve_default=False,
        ),
    ]
